// <auto-generated>
// Rewired Constants
// This list was generated on 18/02/2019 21:55:34
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Horizontal movement")]
        public const int MOVEHORIZONTAL = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Vertical movement")]
        public const int MOVEVERTICAL = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Swim a bit")]
        public const int SWIM = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Fire shrimp")]
        public const int FIRE = 3;
    }
    public static partial class Category {
        public const int DEFAULT = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int DEFAULT = 0;
        }
        public static partial class Keyboard {
            public const int DEFAULT = 0;
        }
        public static partial class Mouse {
            public const int DEFAULT = 0;
        }
        public static partial class CustomController {
            public const int DEFAULT = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int SYSTEM = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player One")]
        public const int ONE = 0;
    }
    public static partial class CustomController {
        public static partial class TouchController {
            public const int SOURCEID = 0;
            public const string NAME = "TouchController";
            public static partial class Axis {
                public const int HORIZONTAL = 0;
                public const int VERTICAL = 1;
            }
            public static partial class Button {
                public const int FIRE = 3;
                public const int SWIM = 4;
            }
        }
    }
}
